import { Purchase } from "@/types/purchase";
import { startOfWeek, endOfWeek, isWithinInterval } from "date-fns";

export interface Insight {
  id: string;
  type: "success" | "warning" | "danger" | "info";
  title: string;
  message: string;
  emoji: string;
}

const LIMITS = {
  MAX_ORDERS_PER_WEEK: 3,
  MAX_ALONE_ORDERS_PER_WEEK: 1,
  MAX_FASTFOOD_LUNCH_PER_WEEK: 1,
};

function getCurrentWeekPurchases(purchases: Purchase[]): Purchase[] {
  const now = new Date();
  const weekStart = startOfWeek(now, { weekStartsOn: 0 }); // Sunday
  const weekEnd = endOfWeek(now, { weekStartsOn: 0 });

  return purchases.filter((purchase) => {
    const purchaseDate = new Date(purchase.date);
    return isWithinInterval(purchaseDate, { start: weekStart, end: weekEnd });
  });
}

function isLunchTime(time: string): boolean {
  const hour = parseInt(time.split(":")[0]);
  return hour >= 11 && hour < 15; // 11am to 3pm
}

function isFastFood(categoryLabel: string): boolean {
  const fastFoodCategories = ["fast food", "fastfood", "fast-food"];
  return fastFoodCategories.some((cat) =>
    categoryLabel.toLowerCase().includes(cat)
  );
}

/**
 * Filters insights by applying a severity-based priority hierarchy.
 * Prevents visual noise by displaying only the most relevant alerts.
 *
 * Priority Hierarchy:
 * 1. **CRITICAL (Danger)**: If any "danger" alert exists, display ONLY all "danger" alerts
 *    - max-orders-reached: Weekly order limit reached (≥3 orders)
 *    - max-alone-orders: Solo order limit reached (≥1 order)
 *
 * 2. **HIGH (Warning)**: If no "danger" exists, display only "warning" alerts
 *    - max-orders-warning: Limit warning (2 orders)
 *    - max-fastfood-lunch: Fast food at lunch time detected
 *    - high-spending: High weekly spending (>R$100)
 *
 * 3. **LOW (Success/Info)**: If no "danger" or "warning" exist, display success/info
 *    - no-orders-yet: No orders this week
 *    - good-behavior: Positive behavior (<3 orders, 0 solo)
 *    - weekly-status: Weekly status information
 *
 * @param insights - Array of insights generated by generateInsights()
 * @returns Filtered array containing only alerts from the highest priority level active
 */
function filterInsightsByPriority(insights: Insight[]): Insight[] {
  // Level 1: Filter critical alerts (danger)
  const dangerInsights = insights.filter(
    (insight) => insight.type === "danger"
  );
  if (dangerInsights.length > 0) {
    return dangerInsights;
  }

  // Level 2: If no danger, filter high priority alerts (warning)
  const warningInsights = insights.filter(
    (insight) => insight.type === "warning"
  );
  if (warningInsights.length > 0) {
    return warningInsights;
  }

  // Level 3: If no danger or warning, return success and info
  return insights.filter(
    (insight) => insight.type === "success" || insight.type === "info"
  );
}

export function generateInsights(
  purchases: Purchase[],
  categories: Array<{ id: string; label: string }>
): Insight[] {
  const insights: Insight[] = [];
  const weekPurchases = getCurrentWeekPurchases(purchases);

  // Weekly statistics
  const totalOrders = weekPurchases.length;
  const aloneOrders = weekPurchases.filter((p) => p.isAlone).length;
  const groupOrders = weekPurchases.filter((p) => !p.isAlone).length;

  // Fast food at lunch time
  const fastFoodLunch = weekPurchases.filter((p) => {
    const category = categories.find((c) => c.id === p.category);
    return category && isFastFood(category.label) && isLunchTime(p.time);
  }).length;

  // 1. Check total orders limit (3 per week)
  if (totalOrders >= LIMITS.MAX_ORDERS_PER_WEEK) {
    insights.push({
      id: "max-orders-reached",
      type: "danger",
      title: "Limite da semana atingido!",
      message: `Você já fez ${totalOrders} pedidos esta semana. Que tal cozinhar ou preparar uma marmita? 🥘`,
      emoji: "🚨",
    });
  } else if (totalOrders === LIMITS.MAX_ORDERS_PER_WEEK - 1) {
    insights.push({
      id: "max-orders-warning",
      type: "warning",
      title: "Penúltimo pedido da semana",
      message: `Você fez ${totalOrders} de ${LIMITS.MAX_ORDERS_PER_WEEK} pedidos permitidos. Só mais 1 esta semana! 🎯`,
      emoji: "⚠️",
    });
  }

  // 2. Check solo orders limit (1 per week)
  if (aloneOrders >= LIMITS.MAX_ALONE_ORDERS_PER_WEEK) {
    insights.push({
      id: "max-alone-orders",
      type: "danger",
      title: "Limite de pedidos sozinho atingido",
      message: `Você já pediu sozinho ${aloneOrders}x esta semana. Próximos pedidos devem ser acompanhados! 👥`,
      emoji: "🚫",
    });
  }

  // 3. Check fast food at lunch limit (1 per week)
  if (fastFoodLunch >= LIMITS.MAX_FASTFOOD_LUNCH_PER_WEEK) {
    insights.push({
      id: "max-fastfood-lunch",
      type: "warning",
      title: "Fast food no almoço já foi!",
      message: `Você já comeu fast food no almoço ${fastFoodLunch}x esta semana. Que tal algo mais saudável? 🥗`,
      emoji: "🍔",
    });
  }

  // 4. Positive insights
  if (totalOrders === 0) {
    insights.push({
      id: "no-orders-yet",
      type: "success",
      title: "Semana impecável! 🎉",
      message: "Você ainda não pediu delivery esta semana. Continue assim!",
      emoji: "✨",
    });
  } else if (totalOrders < LIMITS.MAX_ORDERS_PER_WEEK && aloneOrders === 0) {
    insights.push({
      id: "good-behavior",
      type: "success",
      title: "Você está indo bem!",
      message: `${totalOrders} pedidos esta semana, todos acompanhados. Ótima escolha! 👏`,
      emoji: "💚",
    });
  }

  // 5. General tips if no critical alerts
  if (
    insights.length === 0 &&
    totalOrders > 0 &&
    totalOrders < LIMITS.MAX_ORDERS_PER_WEEK
  ) {
    const remaining = LIMITS.MAX_ORDERS_PER_WEEK - totalOrders;
    const remainingAlone = LIMITS.MAX_ALONE_ORDERS_PER_WEEK - aloneOrders;

    insights.push({
      id: "weekly-status",
      type: "info",
      title: "Status da semana",
      message: `${totalOrders}/${
        LIMITS.MAX_ORDERS_PER_WEEK
      } pedidos feitos. Restam ${remaining} pedidos${
        remainingAlone > 0
          ? ` (${remainingAlone} pode ser sozinho)`
          : " (apenas acompanhados)"
      }.`,
      emoji: "📊",
    });
  }

  // 6. Check weekly spending
  const weekTotal = weekPurchases.reduce((sum, p) => sum + p.valuePaid, 0);
  if (weekTotal > 100) {
    insights.push({
      id: "high-spending",
      type: "warning",
      title: "Gastos altos esta semana",
      message: `Você já gastou R$ ${weekTotal
        .toFixed(2)
        .replace(".", ",")} esta semana. Fique de olho! 💰`,
      emoji: "💸",
    });
  }

  // Apply insight prioritization to avoid visual overload
  // Hierarchy: Danger → Warning → Success/Info
  return filterInsightsByPriority(insights);
}

export function getInsightColor(type: Insight["type"]): {
  bg: string;
  border: string;
  text: string;
  iconBg: string;
} {
  switch (type) {
    case "success":
      return {
        bg: "bg-green-50 dark:bg-green-950/20",
        border: "border-green-200 dark:border-green-800",
        text: "text-green-800 dark:text-green-200",
        iconBg: "bg-green-100 dark:bg-green-900/30",
      };
    case "warning":
      return {
        bg: "bg-yellow-50 dark:bg-yellow-950/20",
        border: "border-yellow-200 dark:border-yellow-800",
        text: "text-yellow-800 dark:text-yellow-200",
        iconBg: "bg-yellow-100 dark:bg-yellow-900/30",
      };
    case "danger":
      return {
        bg: "bg-red-50 dark:bg-red-950/20",
        border: "border-red-200 dark:border-red-800",
        text: "text-red-800 dark:text-red-200",
        iconBg: "bg-red-100 dark:bg-red-900/30",
      };
    case "info":
      return {
        bg: "bg-blue-50 dark:bg-blue-950/20",
        border: "border-blue-200 dark:border-blue-800",
        text: "text-blue-800 dark:text-blue-200",
        iconBg: "bg-blue-100 dark:bg-blue-900/30",
      };
  }
}
